name: transmission
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - alsa-lib=1.2.3.2
  - aom=3.6.0
  - asf_search=10.1.2
  - asf_search-base=10.1.2
  - asttokens=3.0.0
  - attrs=25.4.0
  - blas=2.137
  - blas-devel=3.9.0
  - blosc=1.21.5
  - boost-cpp=1.74.0
  - bottleneck=1.4.2
  - branca=0.8.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - cfitsio=4.0.0
  - charset-normalizer=3.4.4
  - ciso8601=2.3.3
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.0.2
  - curl=7.86.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dateparser=1.2.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fiona=1.8.20
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.13.3
  - freexl=1.0.6
  - fribidi=1.0.10
  - gdal=3.4.0
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h2=4.3.0
  - h5py=3.7.0
  - harfbuzz=3.1.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=68.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9e
  - json-c=0.15
  - jupyter_client=7.3.4
  - jupyter_core=5.9.1
  - kealib=1.4.15
  - keyutils=1.6.3
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.10
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal=3.4.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.17
  - libidn2=2.3.2
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=13.5
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.3
  - libxkbfile=1.1.0
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.9.2
  - libzlib=1.2.13
  - lmdb=0.9.29
  - lz4-c=1.9.3
  - mapclassify=2.8.1
  - markupsafe=2.1.1
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.2.1
  - mesalib=18.3.1
  - minizip=1.2
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - nspr=4.37
  - nss=3.100
  - numexpr=2.11.0
  - numpy=1.26.4
  - olefile=0.47
  - openblas=0.3.30
  - openblas-devel=0.3.30
  - openjpeg=2.5.0
  - openldap=2.6.3
  - openpyxl=3.1.5
  - openssl=1.1.1w
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - poppler=21.11.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - proj=8.2.0
  - prompt-toolkit=3.0.52
  - psutil=5.9.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygeos=0.12.0
  - pygments=2.19.2
  - pyogrio=0.2.0
  - pyparsing=3.2.5
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt=5.12.9
  - rasterio=1.2.10
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.11.3
  - remotezip=0.12.3
  - requests=2.32.5
  - rtree=1.4.1
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - shapely=1.8.0
  - six=1.17.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tenacity=8.2.2
  - threadpoolctl=3.6.0
  - tiledb=2.5.3
  - tk=8.6.15
  - tornado=6.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzcode=2025b
  - tzdata=2025b
  - tzlocal=5.3.1
  - unicodedata2=14.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.3
  - xkeyboard-config=2.31
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/zchen66/.conda/envs/tansmission
